#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cp -f $DIR/.bash_aliases ~
cp -f $DIR/.bash_profile ~
cp -f $DIR/.gitconfig ~
cp -f $DIR/.vimrc ~

$DIR/sync-helpers/gnome-terminal-profile.sh
$DIR/sync-helpers/sublime-seti-theme.sh
$DIR/sync-helpers/sublime-preferences.sh
